# Generated by Django 5.1.1 on 2025-01-20 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_alter_company_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AfterSalesService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('specification', models.CharField(max_length=200)),
                ('capacity', models.IntegerField()),
                ('unit', models.CharField(choices=[('watt', 'watt'), ('kw', 'kw')], max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='after_sales_services', to='accounts.userprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Battery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('brand_name', models.CharField(max_length=200)),
                ('system_type', models.CharField(choices=[('tubular', 'tubular'), ('lithium', 'lithium')], max_length=20)),
                ('specification', models.CharField(max_length=200)),
                ('capacity', models.IntegerField()),
                ('unit', models.CharField(choices=[('watt', 'watt'), ('kw', 'kw')], max_length=10)),
                ('price', models.IntegerField()),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batteries', to='accounts.userprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Bms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('brand_name', models.CharField(blank=True, max_length=200, null=True)),
                ('specification', models.CharField(max_length=200)),
                ('capacity', models.IntegerField()),
                ('unit', models.CharField(choices=[('watt', 'watt'), ('kw', 'kw')], max_length=10)),
                ('price', models.IntegerField()),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bms', to='accounts.userprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CivilWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('specification', models.CharField(max_length=200)),
                ('capacity', models.IntegerField()),
                ('unit', models.CharField(choices=[('watt', 'watt'), ('kw', 'kw')], max_length=10)),
                ('price', models.IntegerField()),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='civil_works', to='accounts.userprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DcEarthing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('specification', models.CharField(max_length=200)),
                ('capacity', models.IntegerField()),
                ('unit', models.CharField(choices=[('watt', 'watt'), ('kw', 'kw')], max_length=10)),
                ('price', models.IntegerField()),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dc_earthings', to='accounts.userprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ElectricWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('specification', models.CharField(max_length=200)),
                ('system_type', models.CharField(choices=[('on_grid', 'on_grid'), ('hybrid', 'hybrid'), ('vfd', 'vfd')], max_length=20)),
                ('unit', models.CharField(choices=[('watt', 'watt'), ('kw', 'kw')], max_length=10)),
                ('price', models.IntegerField()),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='electrical_works', to='accounts.userprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HseEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('specification', models.CharField(max_length=200)),
                ('capacity', models.IntegerField()),
                ('unit', models.CharField(choices=[('watt', 'watt'), ('kw', 'kw')], max_length=10)),
                ('price', models.IntegerField()),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hse_equipments', to='accounts.userprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Inverter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('brand_name', models.CharField(max_length=200)),
                ('system_type', models.CharField(choices=[('on_grid', 'on_grid'), ('hybrid', 'hybrid'), ('vfd', 'vfd')], max_length=20)),
                ('specification', models.CharField(max_length=200)),
                ('capacity', models.IntegerField()),
                ('unit', models.CharField(choices=[('watt', 'watt'), ('kw', 'kw')], max_length=10)),
                ('price', models.IntegerField()),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inverters', to='accounts.userprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MechanicalWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('structure_type', models.CharField(choices=[('iron_standard', 'iron_standard'), ('aluminum_standard', 'aluminum_standard'), ('ms_iron_standard', 'ms_iron_standard')], max_length=20)),
                ('specification', models.CharField(max_length=200)),
                ('unit', models.CharField(choices=[('watt', 'watt'), ('kw', 'kw')], max_length=10)),
                ('price', models.IntegerField()),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mechanical_works', to='accounts.userprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NetMetering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('specification', models.CharField(max_length=200)),
                ('capacity', models.IntegerField()),
                ('unit', models.CharField(choices=[('watt', 'watt'), ('kw', 'kw')], max_length=10)),
                ('price', models.IntegerField()),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='net_meterings', to='accounts.userprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OnlineMonitoring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('specification', models.CharField(max_length=200)),
                ('capacity', models.IntegerField()),
                ('unit', models.CharField(choices=[('watt', 'watt'), ('kw', 'kw')], max_length=10)),
                ('price', models.IntegerField()),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='online_monitorings', to='accounts.userprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Panel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('brand_name', models.CharField(max_length=200)),
                ('specification', models.CharField(max_length=200)),
                ('capacity', models.IntegerField()),
                ('unit', models.CharField(choices=[('watt', 'watt'), ('kw', 'kw')], max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='panels', to='accounts.userprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
