# Generated by Django 5.1.1 on 2024-12-08 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0002_company_city"),
    ]

    operations = [
        migrations.CreateModel(
            name="Panel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("brand_name", models.CharField(max_length=200)),
                ("specification", models.CharField(max_length=200)),
                ("capacity", models.IntegerField()),
                (
                    "unit",
                    models.CharField(
                        choices=[("watt", "watt"), ("kw", "kw")], max_length=10
                    ),
                ),
                ("price", models.IntegerField()),
                (
                    "seller",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_list",
                        to="accounts.userprofile",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
