# Generated by Django 5.1.1 on 2024-12-28 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_company_name'),
        ('pricelist', '0002_alter_panel_seller_aftersalesservice_battery_bms_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aftersalesservice',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='after_sales_services', to='accounts.userprofile'),
        ),
        migrations.AlterField(
            model_name='battery',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batteries', to='accounts.userprofile'),
        ),
        migrations.AlterField(
            model_name='bms',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bms', to='accounts.userprofile'),
        ),
        migrations.AlterField(
            model_name='civilwork',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='civil_works', to='accounts.userprofile'),
        ),
        migrations.AlterField(
            model_name='dcearthing',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dc_earthings', to='accounts.userprofile'),
        ),
        migrations.AlterField(
            model_name='electricwork',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='electrical_works', to='accounts.userprofile'),
        ),
        migrations.AlterField(
            model_name='hseequipment',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hse_equipments', to='accounts.userprofile'),
        ),
        migrations.AlterField(
            model_name='inverter',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inverters', to='accounts.userprofile'),
        ),
        migrations.AlterField(
            model_name='mechanicalwork',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mechanical_works', to='accounts.userprofile'),
        ),
        migrations.AlterField(
            model_name='netmetering',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='net_meterings', to='accounts.userprofile'),
        ),
        migrations.AlterField(
            model_name='onlinemonitoring',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='online_monitorings', to='accounts.userprofile'),
        ),
        migrations.AlterField(
            model_name='panel',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='panels', to='accounts.userprofile'),
        ),
    ]
