# Generated by Django 5.1.1 on 2024-12-29 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricelist', '0003_alter_aftersalesservice_seller_alter_battery_seller_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bms',
            name='brand_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
