# Generated by Django 5.1.1 on 2025-01-19 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricelist', '0004_bms_brand_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aftersalesservice',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='panel',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
