# Generated by Django 5.1.1 on 2024-10-08 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solutiondetails',
            name='material',
        ),
        migrations.RemoveField(
            model_name='solutiondetails',
            name='structure_type',
        ),
        migrations.AddField(
            model_name='solutiondetails',
            name='civil_material',
            field=models.CharField(blank=True, choices=[('Concrete', 'Concrete'), ('Curbstone', 'Curbstone'), ('Brick', 'Brick'), ('Other', 'Other')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='solutiondetails',
            name='mechanical_material',
            field=models.CharField(blank=True, choices=[('Iron', 'Iron'), ('Aluminium', 'Aluminium'), ('GI', 'GI'), ('PVC', 'PVC'), ('Other', 'Other')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='solutiondetails',
            name='mechanical_structure_type',
            field=models.CharField(blank=True, choices=[('L2', 'L2'), ('L3', 'L3'), ('Special', 'Special'), ('Sawtooth', 'Sawtooth'), ('Other', 'Other')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='solutiondetails',
            name='wire_material',
            field=models.CharField(blank=True, choices=[('Copper', 'Copper'), ('Silver', 'Silver'), ('Other', 'Other')], max_length=50, null=True),
        ),
    ]
