# Generated by Django 5.1.1 on 2024-10-10 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_remove_solutiondetails_material_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyerInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('whatsapp_number', models.CharField(max_length=15)),
                ('solar_solution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='listings.solarsolution')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
