# Generated by Django 5.1.1 on 2024-10-16 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_buyerinteraction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='solution',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='service', to='listings.solarsolution'),
        ),
    ]
