# Generated by Django 5.1.1 on 2024-10-17 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_alter_service_solution'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SolutionDetails',
            new_name='SolutionComponent',
        ),
    ]
