# Generated by Django 5.1.1 on 2024-10-17 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_rename_solutiondetails_solutioncomponent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solutioncomponent',
            old_name='details_type',
            new_name='component_type',
        ),
    ]
