# Generated by Django 5.1.1 on 2024-10-18 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_rename_details_type_solutioncomponent_component_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solutioncomponent',
            name='solar_solution',
        ),
        migrations.AddField(
            model_name='solarsolution',
            name='components',
            field=models.ManyToManyField(blank=True, related_name='solar_solutions', to='listings.solutioncomponent'),
        ),
    ]
