# Generated by Django 5.1.1 on 2024-10-29 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_remove_solutioncomponent_solar_solution_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='fire_extinguisher_included',
            new_name='hse_equipment_included',
        ),
        migrations.AddField(
            model_name='service',
            name='transportation_distance',
            field=models.PositiveIntegerField(blank=True, help_text='Enter the distance if transportation is included.', null=True),
        ),
        migrations.AddField(
            model_name='solutioncomponent',
            name='ip_rating',
            field=models.CharField(blank=True, help_text='Enter the IP rating (e.g., IP65, IP67)', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='solutioncomponent',
            name='subtype',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='solutioncomponent',
            name='total_backup_capacity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
