# Generated by Django 5.1.1 on 2024-11-09 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0009_solarsolution_seller_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solarsolution',
            name='size',
            field=models.PositiveIntegerField(help_text='Solution size in kW (e.g., 5.00 kW)'),
        ),
    ]
