# Generated by Django 5.1.1 on 2024-12-10 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_company_city'),
        ('listings', '0010_alter_solarsolution_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solarsolution',
            name='seller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solar_solutions', to='accounts.userprofile'),
        ),
    ]
