# Generated by Django 5.1.1 on 2024-10-07 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('admin_verified', models.BooleanField(default=False, help_text='Has the admin verified the listing?')),
                ('discrepancy', models.TextField(blank=True, help_text='Details of any discrepancy found during review', null=True)),
                ('discrepancy_resolved', models.BooleanField(default=False, help_text='Has the discrepancy been resolved?')),
                ('email_notification_sent', models.BooleanField(default=False, help_text='Has the approval notification been sent to the seller?')),
                ('solution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='listings.solarsolution')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
