# Generated by Django 5.1.1 on 2024-10-26 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_remove_solutioncomponent_solar_solution_and_more'),
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approval',
            name='solution',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='approval', to='listings.solarsolution'),
        ),
    ]
